# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parameter_Input.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.setEnabled(True)
        Dialog.resize(1100, 702)
        Dialog.setBaseSize(QtCore.QSize(400, 400))
        Dialog.setStyleSheet("background-color: rgb(240, 240, 240);")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(6, 6, 111, 31))
        self.label.setStyleSheet("font: 11pt \"Arial\";")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 40, 951, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(790, 600, 231, 81))
        self.buttonBox.setStyleSheet("font: 87 10pt \"Cooper Std Black\";")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 101, 41))
        self.label_9.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 101, 31))
        self.label_8.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 240, 101, 31))
        self.label_10.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 320, 141, 41))
        self.label_11.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_11.setObjectName("label_11")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(150, 80, 281, 31))
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(460, 80, 191, 31))
        self.label_2.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(460, 240, 161, 31))
        self.label_3.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(460, 160, 151, 31))
        self.label_6.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(460, 310, 191, 41))
        self.label_4.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(460, 410, 131, 31))
        self.label_7.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(460, 480, 171, 31))
        self.label_5.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(150, 160, 281, 31))
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(150, 240, 281, 31))
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(700, 80, 241, 31))
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.plainTextEdit_13 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_13.setGeometry(QtCore.QRect(700, 160, 241, 31))
        self.plainTextEdit_13.setObjectName("plainTextEdit_13")
        self.plainTextEdit_14 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_14.setGeometry(QtCore.QRect(700, 240, 241, 31))
        self.plainTextEdit_14.setObjectName("plainTextEdit_14")
        self.plainTextEdit_15 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_15.setGeometry(QtCore.QRect(700, 320, 241, 31))
        self.plainTextEdit_15.setObjectName("plainTextEdit_15")
        self.plainTextEdit_16 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_16.setGeometry(QtCore.QRect(700, 400, 241, 31))
        self.plainTextEdit_16.setObjectName("plainTextEdit_16")
        self.plainTextEdit_17 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_17.setGeometry(QtCore.QRect(700, 480, 241, 31))
        self.plainTextEdit_17.setObjectName("plainTextEdit_17")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(150, 330, 281, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parameter Input"))
        self.label.setText(_translate("Dialog", "Propagator:HPOP"))
        self.label_9.setText(_translate("Dialog", "Stop Time:"))
        self.label_8.setText(_translate("Dialog", "Start Time:"))
        self.label_10.setText(_translate("Dialog", "Step Size:"))
        self.label_11.setText(_translate("Dialog", "Coord System:"))
        self.plainTextEdit_8.setPlainText(_translate("Dialog", "SEC/MIN/HR/DAY/MONTH/YEAR"))
        self.label_2.setText(_translate("Dialog", "Semimajor Axis:"))
        self.label_3.setText(_translate("Dialog", "Eccentricity:"))
        self.label_6.setText(_translate("Dialog", "Inclination:"))
        self.label_4.setText(_translate("Dialog", "Argument of Perigee:"))
        self.label_7.setText(_translate("Dialog", "RAAN:"))
        self.label_5.setText(_translate("Dialog", "True Anomaly:"))
        self.plainTextEdit_10.setPlainText(_translate("Dialog", "SEC/MIN/HR/DAY/MONTH/YEAR"))
        self.plainTextEdit_11.setPlainText(_translate("Dialog", "1s"))
        self.plainTextEdit_9.setPlainText(_translate("Dialog", "7000 km"))
        self.plainTextEdit_13.setPlainText(_translate("Dialog", "45 deg"))
        self.plainTextEdit_14.setPlainText(_translate("Dialog", "0.1"))
        self.plainTextEdit_15.setPlainText(_translate("Dialog", "12 deg"))
        self.plainTextEdit_16.setPlainText(_translate("Dialog", "12 deg"))
        self.plainTextEdit_17.setPlainText(_translate("Dialog", "0 deg"))
        self.comboBox.setItemText(0, _translate("Dialog", "GCRF"))
        self.comboBox.setItemText(1, _translate("Dialog", "J2000"))

